<?xml version="1.0"?>

<robot name="ros_urdf" xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="head_length_x" value="0.3"/>
    <xacro:property name="head_width" value="0.3"/>
    <xacro:property name="head_height" value="0.3"/>
    <xacro:property name="head_mass" value="1.0"/>

    <xacro:property name="head_x" value="0.0"/>
    <xacro:property name="head_y" value="0.0"/>
    <xacro:property name="head_z" value="0.9"/>

    


    <xacro:property name="wheel_radius" value="0.13"/>
    <xacro:property name="wheel_thickness" value="0.09"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    
    <xacro:property name="arm_thickness" value="0.3"/>
    <xacro:property name="arm_radius" value="0.05"/>
    
    
    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- start -->
    <!-- 머리  -->
    <link name="base_link">
        <visual>
            <origin xyz="${head_x} ${head_y} ${head_z}"/>

            <geometry>
                <box size="${head_length_x} ${head_width} ${head_height}"/>
            </geometry>
            
            <material name="orange"/>
        </visual>

        <collision>
            <origin xyz="${head_x} ${head_y} ${head_z}"/>
            <geometry>
                <box size="${head_length_x} ${head_width} ${head_height}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="0.5" x="${head_length_x}" y="${head_width}" z="${head_height}">
            <origin xyz="${head_x} ${head_y} ${head_z}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    
    <joint name="head_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_link_1"/>
        <origin xyz="${head_x} ${head_y} 0"/>
    </joint>
    

    <!-- base 1    가슴    -->
    <link name="base_link_1">
        <visual>
            <origin xyz="0 0 0.6"/>

            <geometry>
                <box size="0.3 0.3 0.1"/>
            </geometry>
            
            <material name="blue"/>
        </visual>

        <collision>
            <origin xyz="0 0 0.6"/>
            <geometry>
                <box size="0.3 0.3 0.1"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="0.5" x="0.3" y="0.3" z="0.1">
            <origin xyz="0 0 0.6" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- left arm    -->
    <joint name="left_arm_joint" type="continuous">
        <parent link="base_link_1"/>
        <child link="left_arm"/>
        <origin xyz="0 0.2 0.6" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_arm">
        <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${arm_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" length="${arm_thickness}" radius="${arm_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="left_arm2_joint" type="continuous">
        <parent link="left_arm"/>
        <child link="left_arm2"/>
        <origin xyz="0 ${arm_thickness+0.2} 0.6" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_arm2">
        <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${arm_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" length="${arm_thickness}" radius="${arm_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- <link name="left_arm">
        <visual>
            <origin xyz="0 0.2 0.6"/>

            <geometry>
                <box size="0.3 0.3 0.1"/>
            </geometry>
            
            <material name="blue"/>
        </visual>

        <collision>
            <origin xyz="0 0.2 0.6"/>
            <geometry>
                <box size="0.3 0.3 0.1"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="0.5" x="0.3" y="0.3" z="0.1">
            <origin xyz="0 0.2 0.6" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link> -->

    <!-- right arm    -->
    <joint name="right_arm_joint" type="continuous">
        <parent link="base_link_1"/>
        <child link="right_arm"/>
        <origin xyz="0 -0.2 0.6" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="right_arm">
        <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_thickness}"/>
            </geometry>
            <material name="red"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${arm_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" length="${arm_thickness}" radius="${arm_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="right_arm2_joint" type="continuous">
        <parent link="right_arm"/>
        <child link="right_arm2"/>
        <origin xyz="0 ${arm_thickness-0.2} 0.6" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="right_arm2">
        <visual>
            <geometry>
                <cylinder radius="${arm_radius}" length="${arm_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${arm_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" length="${arm_thickness}" radius="${arm_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <!-- <link name="right_arm">
        <visual>
            <origin xyz="0 -0.2 0.6"/>

            <geometry>
                <box size="0.3 0.3 0.1"/>
            </geometry>
            
            <material name="red"/>
        </visual>

        <collision>
            <origin xyz="0 -0.2 0.6"/>
            <geometry>
                <box size="0.3 0.3 0.1"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="0.5" x="0.3" y="0.3" z="0.1">
            <origin xyz="0 -0.2 0.6" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link> -->

    <!-- base 2    배    -->
    <joint name="base2_joint" type="fixed">
        <parent link="base_link_1"/>
        <child link="base_link_2"/>
        <origin xyz="${head_x} ${head_y} 0"/>
    </joint>

        
    <link name="base_link_2">
        <visual>
            <origin xyz="0 0 0.3"/>

            <geometry>
                <box size="0.3 0.3 0.1"/>
            </geometry>
            
            <material name="black"/>
        </visual>

        <collision>
            <origin xyz="0 0 0.3"/>
            <geometry>
                <box size="0.3 0.3 0.1"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="0.5" x="0.3" y="0.3" z="0.1">
            <origin xyz="0 0 0.3" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- base 2    배    -->
    <joint name="bottom_joint" type="fixed">
        <parent link="base_link_2"/>
        <child link="bottom"/>
        <origin xyz="${head_x} ${head_y} 0"/>
    </joint>

        
    <link name="bottom">
        <visual>
            <origin xyz="0 0 0.1"/>

            <geometry>
                <box size="0.3 0.3 0.1"/>
            </geometry>
            
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="0 0 0.1"/>
            <geometry>
                <box size="0.3 0.3 0.1"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="0.5" x="0.3" y="0.3" z="0.1">
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- left_wheel    -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="bottom"/>
        <child link="left_wheel"/>
        <origin xyz="0 0.2 0.1" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- right_wheel    -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="bottom"/>
        <child link="right_wheel"/>
        <origin xyz="0 -0.2 0.1" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="red"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


</robot>